### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by tom031** [tom031/tom031.github.io#6]
```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:40:in `block in setup': You have already activated jekyll-sass-converter 1.4.0, but your Gemfile requires jekyll-sass-converter 1.3.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:25:in `map'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/runtime.rb:25:in `setup'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler.rb:99:in `setup'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.0/exe/jekyll:9:in `<top (required)>'
        from C:/tools/ruby23/bin/jekyll:22:in `load'
        from C:/tools/ruby23/bin/jekyll:22:in `<main>'
```

**Comment by tom031** [comment]
You have already activated jekyll-sass-converter 1.4.0, but your Gemfile requires jekyll-sass-converter 1.3.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
run `bundle exec  jekyll s` the server will run on this branch

**Comment by tom031** [comment]
Reinstall Ruby downgrade to 2.2 according to the `doc` and reinstall bundler.
following the `doc` doesn't create a Jekyll template, using `jekyll new` to an empty folder to generate a template and copy to the site repo.
